packages:
  - 'demos/*'
  - 'packages/*'

catalog:
  '@antfu/eslint-config': ^3.8.0
  '@commitlint/cli': ^19.5.0
  '@commitlint/config-conventional': ^19.5.0
  '@commitlint/types': ^19.5.0
  '@commitlint/is-ignored': ^19.5.0
  '@eslint-react/eslint-plugin': ^1.15.0
  '@prettier/plugin-xml': ^3.4.1
  eslint: ^9.13.0
  eslint-plugin-format: ^0.1.2
  eslint-plugin-react-hooks: ^5.0.0
  eslint-plugin-react-refresh: ^0.4.14
  husky: ^9.1.6
  lint-staged: ^15.2.10
  typescript: ^5.5.4
  eslint-plugin-tailwindcss: ^3.17.5
  '@next/eslint-plugin-next': 15.0.1
