packages:
  - 'demos/*'
  - 'packages/*'

catalog:
  '@antfu/eslint-config': ^5.2.1
  '@commander-js/extra-typings': 12.1.0
  '@commitlint/cli': ^19.8.0
  '@commitlint/config-conventional': ^19.8.0
  '@commitlint/is-ignored': ^19.8.0
  '@commitlint/types': ^19.8.0
  '@eslint-react/eslint-plugin': ^1.34.1
  '@next/eslint-plugin-next': ^15.2.2
  '@prettier/plugin-xml': ^3.4.1
  commander: ^12.1.0
  eslint: ^9.22.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.19
  eslint-plugin-tailwindcss: ^3.18.0
  husky: ^9.1.7
  lint-staged: ^15.5.0
  tsx: ^4.19.2
  typescript: ^5.5.4
  vite: ^5.4.8
  vite-plugin-dts: ^4.2.4
  vite-tsconfig-paths: ^5.0.1
  zx: ^8.2.4
