packages:
  - 'demos/*'
  - 'packages/*'

catalog:
  '@antfu/eslint-config': ^3.4.1
  '@commitlint/cli': ^19.4.0
  '@commitlint/config-conventional': ^19.2.2
  '@commitlint/types': ^19.0.3
  '@eslint-react/eslint-plugin': ^1.13.0
  '@prettier/plugin-xml': ^3.4.1
  eslint: ^9.10.0
  eslint-plugin-format: ^0.1.2
  eslint-plugin-react-hooks: ^5.1.0-beta-26f2496093-20240514
  eslint-plugin-react-refresh: ^0.4.11
  husky: ^9.1.5
  lint-staged: ^15.2.10
  typescript: ^5.5.4
